
export const GENRES = [
    "Programming",
    "Web Development",
    "Mobile Development",
    "Artificial Intelligence",
    "Data Science",
    "Cyber Security",
    "Cloud Computing",
    "Technology",
    "Business",
    "Finance",
    "Marketing",
    "Self Improvement",
    "Education",
    "Science",
    "History",
    "Biography",
    "Health & Fitness",
    "Lifestyle",
    "Fiction",
    "Fantasy",
    "Mystery",
    "Thriller",
    "Romance",
    "Horror",
];
